name: CI 👷

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Setup OpenTofu
      uses: opentofu/setup-opentofu@main

    - name: Tofu init
      run: tofu init

    - name: Tofu fmt
      run: tofu fmt --recursive --check

    - name: Validate Lifecycle Manager
      run: |
        # If the ./lifecycle_manager/main.py file has been modified, make sure the zip file was rebuilt
        if git diff --name-only origin/${{ github.base_ref }}..HEAD | grep -q "lifecycle_manager/main.py"; then
          echo "Lifecycle Manager main.py has been modified, checking zip file..."
          cd lifecycle_manager
          
          # Check if the committed zip contains the current main.py content
          if cmp -s <(unzip -p ec2-workerpool-lifecycle-manager.zip main.py) <(cat main.py); then
            echo "Lifecycle Manager zip file contains the current main.py content."
          else
            echo "ERROR: Lifecycle Manager zip file is not up to date!"
            echo "The zip file content doesn't match the current main.py."
            echo "Please rebuild the zip file using './build_lifecycle_manager.sh' and commit the updated zip."
            exit 1
          fi
        else
          echo "Lifecycle Manager main.py has not been modified, skipping zip file check."
        fi